apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: t6oq03qyl-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: t6oq03qyl-python 
  name: t6oq03qyl-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: t6oq03qyl-python 
