apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: t6oq03qyl-python
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-81d01a5e05.fwiy.p3.openshiftapps.com/rhtap/rhtap-qe:b39dbea89e9cf0ab17982e4309ff619c1b23095e@sha256:9cecf36080e717f53e720fcd4f1bfd3935f60b7712568e6e22a4d0ed33f32986
          name: container-image
